ALTER TABLE uploads ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE uploads ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE uploads ADD COLUMN duration_ms INTEGER NOT NULL DEFAULT 0;
