// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const addReaction = `-- name: AddReaction :execrows
INSERT OR IGNORE INTO reactions (message_id, user_id, emoji, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type AddReactionParams struct {
	MessageID string `json:"message_id"`
	UserID    string `json:"user_id"`
	Emoji     string `json:"emoji"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addReaction,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const attachUpload = `-- name: AttachUpload :exec
INSERT OR IGNORE INTO message_attachments (message_id, upload_id, created_at)
VALUES (?1, ?2, ?3)
`

type AttachUploadParams struct {
	MessageID string `json:"message_id"`
	UploadID  string `json:"upload_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) AttachUpload(ctx context.Context, arg AttachUploadParams) error {
	_, err := q.db.ExecContext(ctx, attachUpload, arg.MessageID, arg.UploadID, arg.CreatedAt)
	return err
}

const channelLastSeq = `-- name: ChannelLastSeq :one
SELECT CAST(COALESCE(MAX(channel_seq), 0) AS INTEGER) AS last_seq
FROM messages
WHERE channel_id = CAST(?1 AS TEXT)
  AND parent_message_id IS NULL
`

func (q *Queries) ChannelLastSeq(ctx context.Context, channelID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, channelLastSeq, channelID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const channelNextSeq = `-- name: ChannelNextSeq :one
SELECT CAST(COALESCE(MAX(channel_seq), 0) + 1 AS INTEGER) AS next_seq
FROM messages
WHERE channel_id = CAST(?1 AS TEXT)
  AND parent_message_id IS NULL
`

func (q *Queries) ChannelNextSeq(ctx context.Context, channelID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, channelNextSeq, channelID)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const channelRouteID = `-- name: ChannelRouteID :one
SELECT COALESCE(route_id, '') AS route_id
FROM channels
WHERE workspace_id = ?1
  AND id = ?2
`

type ChannelRouteIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) ChannelRouteID(ctx context.Context, arg ChannelRouteIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, channelRouteID, arg.WorkspaceID, arg.ID)
	var route_id string
	err := row.Scan(&route_id)
	return route_id, err
}

const deleteMessageBody = `-- name: DeleteMessageBody :exec
UPDATE messages
SET body = '',
    deleted_at = ?1
WHERE id = ?2
`

type DeleteMessageBodyParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteMessageBody(ctx context.Context, arg DeleteMessageBodyParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageBody, arg.DeletedAt, arg.ID)
	return err
}

const directConversationMemberIDs = `-- name: DirectConversationMemberIDs :many
SELECT dcm.user_id
FROM direct_conversation_members dcm
JOIN direct_conversations dc ON dc.id = dcm.conversation_id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
WHERE dcm.conversation_id = ?1
ORDER BY dcm.user_id
`

func (q *Queries) DirectConversationMemberIDs(ctx context.Context, conversationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, directConversationMemberIDs, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const directConversationMembers = `-- name: DirectConversationMembers :many
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM users u
JOIN direct_conversation_members dcm ON dcm.user_id = u.id
WHERE dcm.conversation_id = ?1
ORDER BY u.display_name
`

type DirectConversationMembersRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) DirectConversationMembers(ctx context.Context, conversationID string) ([]DirectConversationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, directConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectConversationMembersRow
	for rows.Next() {
		var i DirectConversationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OwnerUserID,
			&i.DisplayName,
			&i.Handle,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const directLastSeq = `-- name: DirectLastSeq :one
SELECT CAST(COALESCE(MAX(channel_seq), 0) AS INTEGER) AS last_seq
FROM messages
WHERE direct_conversation_id = CAST(?1 AS TEXT)
  AND parent_message_id IS NULL
`

func (q *Queries) DirectLastSeq(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, directLastSeq, conversationID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const directNextSeq = `-- name: DirectNextSeq :one
SELECT CAST(COALESCE(MAX(channel_seq), 0) + 1 AS INTEGER) AS next_seq
FROM messages
WHERE direct_conversation_id = CAST(?1 AS TEXT)
`

func (q *Queries) DirectNextSeq(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, directNextSeq, conversationID)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const directRouteID = `-- name: DirectRouteID :one
SELECT COALESCE(dc.route_id, '') AS route_id
FROM direct_conversations dc
JOIN direct_conversation_members dcm ON dcm.conversation_id = dc.id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
WHERE dc.workspace_id = ?1
  AND dc.id = ?2
  AND dcm.user_id = ?3
`

type DirectRouteIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) DirectRouteID(ctx context.Context, arg DirectRouteIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, directRouteID, arg.WorkspaceID, arg.ID, arg.UserID)
	var route_id string
	err := row.Scan(&route_id)
	return route_id, err
}

const firstUser = `-- name: FirstUser :one
SELECT id, kind, owner_user_id, display_name, handle, avatar_url, created_at
FROM users
ORDER BY created_at
LIMIT 1
`

type FirstUserRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) FirstUser(ctx context.Context) (FirstUserRow, error) {
	row := q.db.QueryRowContext(ctx, firstUser)
	var i FirstUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const firstWorkspace = `-- name: FirstWorkspace :one
SELECT id, COALESCE(route_id, '') AS route_id, name, slug, created_at
FROM workspaces
ORDER BY created_at
LIMIT 1
`

type FirstWorkspaceRow struct {
	ID        string `json:"id"`
	RouteID   string `json:"route_id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) FirstWorkspace(ctx context.Context) (FirstWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, firstWorkspace)
	var i FirstWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getBotTokenAuth = `-- name: GetBotTokenAuth :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at,
       bt.id AS token_id, bt.workspace_id, bt.scopes_json
FROM bot_tokens bt
JOIN users u ON u.id = bt.bot_user_id
WHERE bt.token_hash = ?1
  AND bt.revoked_at IS NULL
`

type GetBotTokenAuthRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
	TokenID     string         `json:"token_id"`
	WorkspaceID string         `json:"workspace_id"`
	ScopesJson  string         `json:"scopes_json"`
}

func (q *Queries) GetBotTokenAuth(ctx context.Context, tokenHash string) (GetBotTokenAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getBotTokenAuth, tokenHash)
	var i GetBotTokenAuthRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.TokenID,
		&i.WorkspaceID,
		&i.ScopesJson,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, COALESCE(route_id, '') AS route_id, workspace_id, name, kind, created_at, archived_at
FROM channels
WHERE id = ?1
`

type GetChannelRow struct {
	ID          string         `json:"id"`
	RouteID     string         `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
	ArchivedAt  sql.NullString `json:"archived_at"`
}

func (q *Queries) GetChannel(ctx context.Context, id string) (GetChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChannelByIDAndWorkspace = `-- name: GetChannelByIDAndWorkspace :one
SELECT id, COALESCE(route_id, '') AS route_id, workspace_id, name, kind, created_at, archived_at
FROM channels
WHERE workspace_id = ?1
  AND id = ?2
`

type GetChannelByIDAndWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

type GetChannelByIDAndWorkspaceRow struct {
	ID          string         `json:"id"`
	RouteID     string         `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
	ArchivedAt  sql.NullString `json:"archived_at"`
}

func (q *Queries) GetChannelByIDAndWorkspace(ctx context.Context, arg GetChannelByIDAndWorkspaceParams) (GetChannelByIDAndWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getChannelByIDAndWorkspace, arg.WorkspaceID, arg.ID)
	var i GetChannelByIDAndWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChannelByRouteIDAndWorkspace = `-- name: GetChannelByRouteIDAndWorkspace :one
SELECT id, COALESCE(route_id, '') AS route_id, workspace_id, name, kind, created_at, archived_at
FROM channels
WHERE workspace_id = ?1
  AND route_id = ?2
`

type GetChannelByRouteIDAndWorkspaceParams struct {
	WorkspaceID string         `json:"workspace_id"`
	RouteID     sql.NullString `json:"route_id"`
}

type GetChannelByRouteIDAndWorkspaceRow struct {
	ID          string         `json:"id"`
	RouteID     string         `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
	ArchivedAt  sql.NullString `json:"archived_at"`
}

func (q *Queries) GetChannelByRouteIDAndWorkspace(ctx context.Context, arg GetChannelByRouteIDAndWorkspaceParams) (GetChannelByRouteIDAndWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getChannelByRouteIDAndWorkspace, arg.WorkspaceID, arg.RouteID)
	var i GetChannelByRouteIDAndWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChannelWorkspace = `-- name: GetChannelWorkspace :one
SELECT workspace_id
FROM channels
WHERE id = ?1
`

func (q *Queries) GetChannelWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getChannelWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getDirectByIDAndWorkspace = `-- name: GetDirectByIDAndWorkspace :one
SELECT dc.id, COALESCE(dc.route_id, '') AS route_id, dc.workspace_id, dc.created_at
FROM direct_conversations dc
JOIN direct_conversation_members dcm ON dcm.conversation_id = dc.id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
WHERE dc.workspace_id = ?1
  AND dc.id = ?2
  AND dcm.user_id = ?3
`

type GetDirectByIDAndWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

type GetDirectByIDAndWorkspaceRow struct {
	ID          string `json:"id"`
	RouteID     string `json:"route_id"`
	WorkspaceID string `json:"workspace_id"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetDirectByIDAndWorkspace(ctx context.Context, arg GetDirectByIDAndWorkspaceParams) (GetDirectByIDAndWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getDirectByIDAndWorkspace, arg.WorkspaceID, arg.ID, arg.UserID)
	var i GetDirectByIDAndWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getDirectByRouteIDAndWorkspace = `-- name: GetDirectByRouteIDAndWorkspace :one
SELECT dc.id, COALESCE(dc.route_id, '') AS route_id, dc.workspace_id, dc.created_at
FROM direct_conversations dc
JOIN direct_conversation_members dcm ON dcm.conversation_id = dc.id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
WHERE dc.workspace_id = ?1
  AND dc.route_id = ?2
  AND dcm.user_id = ?3
`

type GetDirectByRouteIDAndWorkspaceParams struct {
	WorkspaceID string         `json:"workspace_id"`
	RouteID     sql.NullString `json:"route_id"`
	UserID      string         `json:"user_id"`
}

type GetDirectByRouteIDAndWorkspaceRow struct {
	ID          string `json:"id"`
	RouteID     string `json:"route_id"`
	WorkspaceID string `json:"workspace_id"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetDirectByRouteIDAndWorkspace(ctx context.Context, arg GetDirectByRouteIDAndWorkspaceParams) (GetDirectByRouteIDAndWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getDirectByRouteIDAndWorkspace, arg.WorkspaceID, arg.RouteID, arg.UserID)
	var i GetDirectByRouteIDAndWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.CreatedAt,
	)
	return i, err
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT dc.id, COALESCE(dc.route_id, '') AS route_id, dc.workspace_id, dc.created_at,
       CAST(COALESCE((SELECT MAX(channel_seq) FROM messages WHERE direct_conversation_id = dc.id AND parent_message_id IS NULL), 0) AS INTEGER) AS last_seq,
       CAST(COALESCE((SELECT dr.last_read_seq FROM direct_reads dr WHERE dr.conversation_id = dc.id AND dr.user_id = ?1), 0) AS INTEGER) AS last_read_seq,
       CAST(COALESCE((
         SELECT COUNT(*)
         FROM messages m
         WHERE m.direct_conversation_id = dc.id
           AND m.parent_message_id IS NULL
           AND m.author_id <> ?1
           AND m.channel_seq > COALESCE((SELECT dr2.last_read_seq FROM direct_reads dr2 WHERE dr2.conversation_id = dc.id AND dr2.user_id = ?1), 0)
       ), 0) AS INTEGER) AS unread_count
FROM direct_conversations dc
JOIN direct_conversation_members dcm ON dcm.conversation_id = dc.id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
WHERE dc.id = ?2
  AND dcm.user_id = ?1
`

type GetDirectConversationParams struct {
	ReaderUserID   string `json:"reader_user_id"`
	ConversationID string `json:"conversation_id"`
}

type GetDirectConversationRow struct {
	ID          string `json:"id"`
	RouteID     string `json:"route_id"`
	WorkspaceID string `json:"workspace_id"`
	CreatedAt   string `json:"created_at"`
	LastSeq     int64  `json:"last_seq"`
	LastReadSeq int64  `json:"last_read_seq"`
	UnreadCount int64  `json:"unread_count"`
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (GetDirectConversationRow, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversation, arg.ReaderUserID, arg.ConversationID)
	var i GetDirectConversationRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.LastSeq,
		&i.LastReadSeq,
		&i.UnreadCount,
	)
	return i, err
}

const getDirectConversationWorkspace = `-- name: GetDirectConversationWorkspace :one
SELECT workspace_id
FROM direct_conversations
WHERE id = ?1
`

func (q *Queries) GetDirectConversationWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversationWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getMagicLinkByToken = `-- name: GetMagicLinkByToken :one
SELECT id, token, token_hash, email, display_name, created_at, expires_at, used_at
FROM auth_magic_links
WHERE token_hash = ?1
`

func (q *Queries) GetMagicLinkByToken(ctx context.Context, tokenHash string) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkByToken, tokenHash)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TokenHash,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT pushover_enabled, pushover_user_key
FROM user_notification_settings
WHERE user_id = ?1
`

type GetNotificationSettingsRow struct {
	PushoverEnabled int64  `json:"pushover_enabled"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) GetNotificationSettings(ctx context.Context, userID string) (GetNotificationSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSettings, userID)
	var i GetNotificationSettingsRow
	err := row.Scan(&i.PushoverEnabled, &i.PushoverUserKey)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?1
  AND s.revoked_at IS NULL
  AND s.expires_at > ?2
`

type GetSessionUserParams struct {
	TokenHash string `json:"token_hash"`
	Now       string `json:"now"`
}

type GetSessionUserRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.Now)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadState = `-- name: GetThreadState :one
SELECT root_message_id, reply_count, last_reply_at, last_reply_author_ids_json
FROM thread_state
WHERE root_message_id = ?1
`

func (q *Queries) GetThreadState(ctx context.Context, rootMessageID string) (ThreadState, error) {
	row := q.db.QueryRowContext(ctx, getThreadState, rootMessageID)
	var i ThreadState
	err := row.Scan(
		&i.RootMessageID,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.LastReplyAuthorIdsJson,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, workspace_id, owner_id, filename, content_type, byte_size, width, height, duration_ms, storage_path, created_at
FROM uploads
WHERE id = ?1
`

type GetUploadRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	OwnerID     string `json:"owner_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
	Width       int64  `json:"width"`
	Height      int64  `json:"height"`
	DurationMs  int64  `json:"duration_ms"`
	StoragePath string `json:"storage_path"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetUpload(ctx context.Context, id string) (GetUploadRow, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i GetUploadRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadWorkspace = `-- name: GetUploadWorkspace :one
SELECT workspace_id
FROM uploads
WHERE id = ?1
`

func (q *Queries) GetUploadWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUploadWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getUser = `-- name: GetUser :one
SELECT id, kind, owner_user_id, display_name, handle, avatar_url, created_at
FROM users
WHERE id = ?1
`

type GetUserRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIdentityEmail = `-- name: GetUserByIdentityEmail :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM identities i
JOIN users u ON u.id = i.user_id
WHERE i.email = ?1
ORDER BY u.created_at
LIMIT 1
`

type GetUserByIdentityEmailRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetUserByIdentityEmail(ctx context.Context, email string) (GetUserByIdentityEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentityEmail, email)
	var i GetUserByIdentityEmailRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIdentityProviderSubject = `-- name: GetUserByIdentityProviderSubject :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = ?1
  AND i.provider_subject = ?2
`

type GetUserByIdentityProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

type GetUserByIdentityProviderSubjectRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetUserByIdentityProviderSubject(ctx context.Context, arg GetUserByIdentityProviderSubjectParams) (GetUserByIdentityProviderSubjectRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentityProviderSubject, arg.Provider, arg.ProviderSubject)
	var i GetUserByIdentityProviderSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT w.id, COALESCE(w.route_id, '') AS route_id, w.name, w.slug, w.created_at
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE w.id = ?1
  AND wm.user_id = ?2
`

type GetWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

type GetWorkspaceRow struct {
	ID        string `json:"id"`
	RouteID   string `json:"route_id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) GetWorkspace(ctx context.Context, arg GetWorkspaceParams) (GetWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByRouteID = `-- name: GetWorkspaceByRouteID :one
SELECT id, COALESCE(route_id, '') AS route_id, name, slug, created_at
FROM workspaces
WHERE route_id = ?1
`

type GetWorkspaceByRouteIDRow struct {
	ID        string `json:"id"`
	RouteID   string `json:"route_id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) GetWorkspaceByRouteID(ctx context.Context, routeID sql.NullString) (GetWorkspaceByRouteIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByRouteID, routeID)
	var i GetWorkspaceByRouteIDRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const insertBotToken = `-- name: InsertBotToken :exec
INSERT INTO bot_tokens (id, token_hash, bot_user_id, workspace_id, owner_user_id, name, scopes_json, created_by, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertBotTokenParams struct {
	ID          string         `json:"id"`
	TokenHash   string         `json:"token_hash"`
	BotUserID   string         `json:"bot_user_id"`
	WorkspaceID string         `json:"workspace_id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	Name        string         `json:"name"`
	ScopesJson  string         `json:"scopes_json"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertBotToken(ctx context.Context, arg InsertBotTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertBotToken,
		arg.ID,
		arg.TokenHash,
		arg.BotUserID,
		arg.WorkspaceID,
		arg.OwnerUserID,
		arg.Name,
		arg.ScopesJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertBotUser = `-- name: InsertBotUser :exec
INSERT INTO users (id, kind, owner_user_id, display_name, handle, avatar_url, created_at)
VALUES (?1, 'bot', ?2, ?3, ?4, ?5, ?6)
`

type InsertBotUserParams struct {
	ID          string         `json:"id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertBotUser(ctx context.Context, arg InsertBotUserParams) error {
	_, err := q.db.ExecContext(ctx, insertBotUser,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertChannel = `-- name: InsertChannel :exec
INSERT INTO channels (id, route_id, workspace_id, name, kind, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertChannelParams struct {
	ID          string         `json:"id"`
	RouteID     sql.NullString `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertChannel,
		arg.ID,
		arg.RouteID,
		arg.WorkspaceID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const insertChannelMessage = `-- name: InsertChannelMessage :exec
INSERT INTO messages (id, workspace_id, channel_id, direct_conversation_id, author_id, parent_message_id, thread_root_id, channel_seq, thread_seq, body, body_format, created_at, quoted_message_id, quoted_body_snapshot, quoted_author_id, client_nonce)
VALUES (?1, ?2, ?3, NULL, ?4, NULL, ?5, ?6, NULL, ?7, 'markdown', ?8, ?9, ?10, ?11, ?12)
`

type InsertChannelMessageParams struct {
	ID                 string         `json:"id"`
	WorkspaceID        string         `json:"workspace_id"`
	ChannelID          sql.NullString `json:"channel_id"`
	AuthorID           string         `json:"author_id"`
	ThreadRootID       string         `json:"thread_root_id"`
	ChannelSeq         sql.NullInt64  `json:"channel_seq"`
	Body               string         `json:"body"`
	CreatedAt          string         `json:"created_at"`
	QuotedMessageID    sql.NullString `json:"quoted_message_id"`
	QuotedBodySnapshot string         `json:"quoted_body_snapshot"`
	QuotedAuthorID     sql.NullString `json:"quoted_author_id"`
	ClientNonce        string         `json:"client_nonce"`
}

func (q *Queries) InsertChannelMessage(ctx context.Context, arg InsertChannelMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertChannelMessage,
		arg.ID,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.AuthorID,
		arg.ThreadRootID,
		arg.ChannelSeq,
		arg.Body,
		arg.CreatedAt,
		arg.QuotedMessageID,
		arg.QuotedBodySnapshot,
		arg.QuotedAuthorID,
		arg.ClientNonce,
	)
	return err
}

const insertDefaultChannel = `-- name: InsertDefaultChannel :exec
INSERT INTO channels (id, route_id, workspace_id, name, kind, created_at)
VALUES (?1, ?2, ?3, 'general', 'public', ?4)
`

type InsertDefaultChannelParams struct {
	ID          string         `json:"id"`
	RouteID     sql.NullString `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertDefaultChannel(ctx context.Context, arg InsertDefaultChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultChannel,
		arg.ID,
		arg.RouteID,
		arg.WorkspaceID,
		arg.CreatedAt,
	)
	return err
}

const insertDefaultWorkspaceMember = `-- name: InsertDefaultWorkspaceMember :exec
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, created_at)
VALUES (?1, ?2, 'member', ?3)
`

type InsertDefaultWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertDefaultWorkspaceMember(ctx context.Context, arg InsertDefaultWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.CreatedAt)
	return err
}

const insertDirectConversation = `-- name: InsertDirectConversation :exec
INSERT INTO direct_conversations (id, route_id, workspace_id, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertDirectConversationParams struct {
	ID          string         `json:"id"`
	RouteID     sql.NullString `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertDirectConversation(ctx context.Context, arg InsertDirectConversationParams) error {
	_, err := q.db.ExecContext(ctx, insertDirectConversation,
		arg.ID,
		arg.RouteID,
		arg.WorkspaceID,
		arg.CreatedAt,
	)
	return err
}

const insertDirectConversationMember = `-- name: InsertDirectConversationMember :exec
INSERT INTO direct_conversation_members (conversation_id, user_id, created_at)
VALUES (?1, ?2, ?3)
`

type InsertDirectConversationMemberParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) InsertDirectConversationMember(ctx context.Context, arg InsertDirectConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertDirectConversationMember, arg.ConversationID, arg.UserID, arg.CreatedAt)
	return err
}

const insertDirectMessage = `-- name: InsertDirectMessage :exec
INSERT INTO messages (id, workspace_id, channel_id, direct_conversation_id, author_id, parent_message_id, thread_root_id, channel_seq, thread_seq, body, body_format, created_at, quoted_message_id, quoted_body_snapshot, quoted_author_id, client_nonce)
VALUES (?1, ?2, NULL, ?3, ?4, NULL, ?5, ?6, NULL, ?7, 'markdown', ?8, ?9, ?10, ?11, ?12)
`

type InsertDirectMessageParams struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	DirectConversationID sql.NullString `json:"direct_conversation_id"`
	AuthorID             string         `json:"author_id"`
	ThreadRootID         string         `json:"thread_root_id"`
	ChannelSeq           sql.NullInt64  `json:"channel_seq"`
	Body                 string         `json:"body"`
	CreatedAt            string         `json:"created_at"`
	QuotedMessageID      sql.NullString `json:"quoted_message_id"`
	QuotedBodySnapshot   string         `json:"quoted_body_snapshot"`
	QuotedAuthorID       sql.NullString `json:"quoted_author_id"`
	ClientNonce          string         `json:"client_nonce"`
}

func (q *Queries) InsertDirectMessage(ctx context.Context, arg InsertDirectMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertDirectMessage,
		arg.ID,
		arg.WorkspaceID,
		arg.DirectConversationID,
		arg.AuthorID,
		arg.ThreadRootID,
		arg.ChannelSeq,
		arg.Body,
		arg.CreatedAt,
		arg.QuotedMessageID,
		arg.QuotedBodySnapshot,
		arg.QuotedAuthorID,
		arg.ClientNonce,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, cursor, workspace_id, channel_id, type, seq, payload_json, created_at, is_private)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertEventParams struct {
	ID          string         `json:"id"`
	Cursor      string         `json:"cursor"`
	WorkspaceID string         `json:"workspace_id"`
	ChannelID   sql.NullString `json:"channel_id"`
	Type        string         `json:"type"`
	Seq         sql.NullInt64  `json:"seq"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   string         `json:"created_at"`
	IsPrivate   int64          `json:"is_private"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Cursor,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.Type,
		arg.Seq,
		arg.PayloadJson,
		arg.CreatedAt,
		arg.IsPrivate,
	)
	return err
}

const insertEventRecipient = `-- name: InsertEventRecipient :exec
INSERT INTO event_recipients (event_id, user_id)
VALUES (?1, ?2)
`

type InsertEventRecipientParams struct {
	EventID string `json:"event_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) InsertEventRecipient(ctx context.Context, arg InsertEventRecipientParams) error {
	_, err := q.db.ExecContext(ctx, insertEventRecipient, arg.EventID, arg.UserID)
	return err
}

const insertHumanUser = `-- name: InsertHumanUser :exec
INSERT INTO users (id, display_name, avatar_url, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertHumanUserParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertHumanUser(ctx context.Context, arg InsertHumanUserParams) error {
	_, err := q.db.ExecContext(ctx, insertHumanUser,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO identities (id, user_id, provider, provider_subject, email, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertIdentityParams struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites (id, workspace_id, token, created_by, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertInviteParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Token       string `json:"token"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Token,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertMagicLink = `-- name: InsertMagicLink :exec
INSERT INTO auth_magic_links (id, token, token_hash, email, display_name, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type InsertMagicLinkParams struct {
	ID          string `json:"id"`
	Token       string `json:"token"`
	TokenHash   string `json:"token_hash"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) InsertMagicLink(ctx context.Context, arg InsertMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertMagicLink,
		arg.ID,
		arg.Token,
		arg.TokenHash,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, token, token_hash, user_id, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertSessionParams struct {
	ID        string `json:"id"`
	Token     string `json:"token"`
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.Token,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertThreadReply = `-- name: InsertThreadReply :exec
INSERT INTO messages (id, workspace_id, channel_id, direct_conversation_id, author_id, parent_message_id, thread_root_id, channel_seq, thread_seq, body, body_format, created_at, quoted_message_id, quoted_body_snapshot, quoted_author_id, client_nonce)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, NULL, ?8, ?9, 'markdown', ?10, ?11, ?12, ?13, ?14)
`

type InsertThreadReplyParams struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	ChannelID            sql.NullString `json:"channel_id"`
	DirectConversationID sql.NullString `json:"direct_conversation_id"`
	AuthorID             string         `json:"author_id"`
	ParentMessageID      sql.NullString `json:"parent_message_id"`
	ThreadRootID         string         `json:"thread_root_id"`
	ThreadSeq            sql.NullInt64  `json:"thread_seq"`
	Body                 string         `json:"body"`
	CreatedAt            string         `json:"created_at"`
	QuotedMessageID      sql.NullString `json:"quoted_message_id"`
	QuotedBodySnapshot   string         `json:"quoted_body_snapshot"`
	QuotedAuthorID       sql.NullString `json:"quoted_author_id"`
	ClientNonce          string         `json:"client_nonce"`
}

func (q *Queries) InsertThreadReply(ctx context.Context, arg InsertThreadReplyParams) error {
	_, err := q.db.ExecContext(ctx, insertThreadReply,
		arg.ID,
		arg.WorkspaceID,
		arg.ChannelID,
		arg.DirectConversationID,
		arg.AuthorID,
		arg.ParentMessageID,
		arg.ThreadRootID,
		arg.ThreadSeq,
		arg.Body,
		arg.CreatedAt,
		arg.QuotedMessageID,
		arg.QuotedBodySnapshot,
		arg.QuotedAuthorID,
		arg.ClientNonce,
	)
	return err
}

const insertThreadState = `-- name: InsertThreadState :exec
INSERT INTO thread_state (root_message_id)
VALUES (?1)
`

func (q *Queries) InsertThreadState(ctx context.Context, rootMessageID string) error {
	_, err := q.db.ExecContext(ctx, insertThreadState, rootMessageID)
	return err
}

const insertUpload = `-- name: InsertUpload :exec
INSERT INTO uploads (id, workspace_id, owner_id, filename, content_type, byte_size, width, height, duration_ms, storage_path, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
`

type InsertUploadParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	OwnerID     string `json:"owner_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
	Width       int64  `json:"width"`
	Height      int64  `json:"height"`
	DurationMs  int64  `json:"duration_ms"`
	StoragePath string `json:"storage_path"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertUpload(ctx context.Context, arg InsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, insertUpload,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.StoragePath,
		arg.CreatedAt,
	)
	return err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspaces (id, route_id, name, slug, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertWorkspaceParams struct {
	ID        string         `json:"id"`
	RouteID   sql.NullString `json:"route_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspace,
		arg.ID,
		arg.RouteID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const insertWorkspaceMember = `-- name: InsertWorkspaceMember :exec
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertWorkspaceMember(ctx context.Context, arg InsertWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const listChannels = `-- name: ListChannels :many
SELECT c.id, COALESCE(c.route_id, '') AS route_id, c.workspace_id, c.name, c.kind, c.created_at, c.archived_at,
       CAST(COALESCE((SELECT MAX(channel_seq) FROM messages WHERE channel_id = c.id AND parent_message_id IS NULL), 0) AS INTEGER) AS last_seq,
       CAST(COALESCE((SELECT cr.last_read_seq FROM channel_reads cr WHERE cr.channel_id = c.id AND cr.user_id = ?1), 0) AS INTEGER) AS last_read_seq,
       CAST(COALESCE((
         SELECT COUNT(*)
         FROM messages m
         WHERE m.channel_id = c.id
           AND m.parent_message_id IS NULL
           AND m.author_id <> ?1
           AND m.channel_seq > COALESCE((SELECT cr2.last_read_seq FROM channel_reads cr2 WHERE cr2.channel_id = c.id AND cr2.user_id = ?1), 0)
       ), 0) AS INTEGER) AS unread_count
FROM channels c
WHERE c.workspace_id = ?2
ORDER BY c.name
`

type ListChannelsParams struct {
	ReaderUserID string `json:"reader_user_id"`
	WorkspaceID  string `json:"workspace_id"`
}

type ListChannelsRow struct {
	ID          string         `json:"id"`
	RouteID     string         `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
	ArchivedAt  sql.NullString `json:"archived_at"`
	LastSeq     int64          `json:"last_seq"`
	LastReadSeq int64          `json:"last_read_seq"`
	UnreadCount int64          `json:"unread_count"`
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]ListChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.ReaderUserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.WorkspaceID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.LastSeq,
			&i.LastReadSeq,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectConversations = `-- name: ListDirectConversations :many
SELECT dc.id, COALESCE(dc.route_id, '') AS route_id, dc.workspace_id, dc.created_at,
       CAST(COALESCE((SELECT MAX(channel_seq) FROM messages WHERE direct_conversation_id = dc.id AND parent_message_id IS NULL), 0) AS INTEGER) AS last_seq,
       CAST(COALESCE((SELECT dr.last_read_seq FROM direct_reads dr WHERE dr.conversation_id = dc.id AND dr.user_id = ?1), 0) AS INTEGER) AS last_read_seq,
       CAST(COALESCE((
         SELECT COUNT(*)
         FROM messages m
         WHERE m.direct_conversation_id = dc.id
           AND m.parent_message_id IS NULL
           AND m.author_id <> ?1
           AND m.channel_seq > COALESCE((SELECT dr2.last_read_seq FROM direct_reads dr2 WHERE dr2.conversation_id = dc.id AND dr2.user_id = ?1), 0)
       ), 0) AS INTEGER) AS unread_count
FROM direct_conversations dc
JOIN direct_conversation_members dcm ON dcm.conversation_id = dc.id
WHERE dc.workspace_id = ?2
  AND dcm.user_id = ?1
ORDER BY dc.created_at
`

type ListDirectConversationsParams struct {
	ReaderUserID string `json:"reader_user_id"`
	WorkspaceID  string `json:"workspace_id"`
}

type ListDirectConversationsRow struct {
	ID          string `json:"id"`
	RouteID     string `json:"route_id"`
	WorkspaceID string `json:"workspace_id"`
	CreatedAt   string `json:"created_at"`
	LastSeq     int64  `json:"last_seq"`
	LastReadSeq int64  `json:"last_read_seq"`
	UnreadCount int64  `json:"unread_count"`
}

func (q *Queries) ListDirectConversations(ctx context.Context, arg ListDirectConversationsParams) ([]ListDirectConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectConversations, arg.ReaderUserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectConversationsRow
	for rows.Next() {
		var i ListDirectConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.LastSeq,
			&i.LastReadSeq,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectPushNotificationRecipients = `-- name: ListDirectPushNotificationRecipients :many
SELECT u.id AS user_id, u.display_name, uns.pushover_user_key
FROM direct_conversation_members dcm
JOIN direct_conversations dc ON dc.id = dcm.conversation_id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
JOIN users u ON u.id = dcm.user_id
JOIN user_notification_settings uns ON uns.user_id = u.id
WHERE dcm.conversation_id = ?1
  AND u.id <> ?2
  AND uns.pushover_enabled = 1
  AND uns.pushover_user_key <> ''
ORDER BY u.id
`

type ListDirectPushNotificationRecipientsParams struct {
	ConversationID string `json:"conversation_id"`
	AuthorID       string `json:"author_id"`
}

type ListDirectPushNotificationRecipientsRow struct {
	UserID          string `json:"user_id"`
	DisplayName     string `json:"display_name"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) ListDirectPushNotificationRecipients(ctx context.Context, arg ListDirectPushNotificationRecipientsParams) ([]ListDirectPushNotificationRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectPushNotificationRecipients, arg.ConversationID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectPushNotificationRecipientsRow
	for rows.Next() {
		var i ListDirectPushNotificationRecipientsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.PushoverUserKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT e.id, e.cursor, e.workspace_id, COALESCE(e.channel_id, '') AS channel_id, e.type, e.seq, e.payload_json, e.created_at
FROM events e
WHERE e.workspace_id = ?1
  AND e.cursor > ?2
  AND (
    e.is_private = 0
    OR EXISTS (SELECT 1 FROM event_recipients er WHERE er.event_id = e.id AND er.user_id = ?3)
  )
ORDER BY e.cursor
LIMIT ?4
`

type ListEventsAfterParams struct {
	WorkspaceID string `json:"workspace_id"`
	Cursor      string `json:"cursor"`
	UserID      string `json:"user_id"`
	LimitCount  int64  `json:"limit_count"`
}

type ListEventsAfterRow struct {
	ID          string        `json:"id"`
	Cursor      string        `json:"cursor"`
	WorkspaceID string        `json:"workspace_id"`
	ChannelID   string        `json:"channel_id"`
	Type        string        `json:"type"`
	Seq         sql.NullInt64 `json:"seq"`
	PayloadJson string        `json:"payload_json"`
	CreatedAt   string        `json:"created_at"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]ListEventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter,
		arg.WorkspaceID,
		arg.Cursor,
		arg.UserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsAfterRow
	for rows.Next() {
		var i ListEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Cursor,
			&i.WorkspaceID,
			&i.ChannelID,
			&i.Type,
			&i.Seq,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacePushNotificationRecipients = `-- name: ListWorkspacePushNotificationRecipients :many
SELECT u.id AS user_id, u.display_name, uns.pushover_user_key
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
JOIN user_notification_settings uns ON uns.user_id = u.id
WHERE wm.workspace_id = ?1
  AND u.id <> ?2
  AND uns.pushover_enabled = 1
  AND uns.pushover_user_key <> ''
ORDER BY u.id
`

type ListWorkspacePushNotificationRecipientsParams struct {
	WorkspaceID string `json:"workspace_id"`
	AuthorID    string `json:"author_id"`
}

type ListWorkspacePushNotificationRecipientsRow struct {
	UserID          string `json:"user_id"`
	DisplayName     string `json:"display_name"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) ListWorkspacePushNotificationRecipients(ctx context.Context, arg ListWorkspacePushNotificationRecipientsParams) ([]ListWorkspacePushNotificationRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacePushNotificationRecipients, arg.WorkspaceID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacePushNotificationRecipientsRow
	for rows.Next() {
		var i ListWorkspacePushNotificationRecipientsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.PushoverUserKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT w.id, COALESCE(w.route_id, '') AS route_id, w.name, w.slug, w.created_at
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = ?1
ORDER BY w.created_at
`

type ListWorkspacesRow struct {
	ID        string `json:"id"`
	RouteID   string `json:"route_id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListWorkspaces(ctx context.Context, userID string) ([]ListWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesRow
	for rows.Next() {
		var i ListWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE auth_magic_links
SET used_at = ?1
WHERE id = ?2
`

type MarkMagicLinkUsedParams struct {
	UsedAt sql.NullString `json:"used_at"`
	ID     string         `json:"id"`
}

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, arg MarkMagicLinkUsedParams) error {
	_, err := q.db.ExecContext(ctx, markMagicLinkUsed, arg.UsedAt, arg.ID)
	return err
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events AS e
WHERE e.workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR julianday(e.created_at) < julianday(CAST(?2 AS TEXT)))
  AND e.id NOT IN (
    SELECT kept.id
    FROM events AS kept
    WHERE kept.workspace_id = ?1
    ORDER BY kept.cursor DESC
    LIMIT ?3
  )
`

type PruneEventsParams struct {
	WorkspaceIDArg string `json:"workspace_id_arg"`
	Before         string `json:"before"`
	KeepLatest     int64  `json:"keep_latest"`
}

func (q *Queries) PruneEvents(ctx context.Context, arg PruneEventsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEvents, arg.WorkspaceIDArg, arg.Before, arg.KeepLatest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readChannelRead = `-- name: ReadChannelRead :one
SELECT last_read_seq, last_read_at
FROM channel_reads
WHERE channel_id = ?1
  AND user_id = ?2
`

type ReadChannelReadParams struct {
	ChannelID string `json:"channel_id"`
	UserID    string `json:"user_id"`
}

type ReadChannelReadRow struct {
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

func (q *Queries) ReadChannelRead(ctx context.Context, arg ReadChannelReadParams) (ReadChannelReadRow, error) {
	row := q.db.QueryRowContext(ctx, readChannelRead, arg.ChannelID, arg.UserID)
	var i ReadChannelReadRow
	err := row.Scan(&i.LastReadSeq, &i.LastReadAt)
	return i, err
}

const readDirectRead = `-- name: ReadDirectRead :one
SELECT last_read_seq, last_read_at
FROM direct_reads
WHERE conversation_id = ?1
  AND user_id = ?2
`

type ReadDirectReadParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

type ReadDirectReadRow struct {
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

func (q *Queries) ReadDirectRead(ctx context.Context, arg ReadDirectReadParams) (ReadDirectReadRow, error) {
	row := q.db.QueryRowContext(ctx, readDirectRead, arg.ConversationID, arg.UserID)
	var i ReadDirectReadRow
	err := row.Scan(&i.LastReadSeq, &i.LastReadAt)
	return i, err
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM reactions
WHERE message_id = ?1
  AND user_id = ?2
  AND emoji = ?3
`

type RemoveReactionParams struct {
	MessageID string `json:"message_id"`
	UserID    string `json:"user_id"`
	Emoji     string `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requireDirectMembership = `-- name: RequireDirectMembership :one
SELECT 1
FROM direct_conversation_members dcm
JOIN direct_conversations dc ON dc.id = dcm.conversation_id
JOIN workspace_members wm ON wm.workspace_id = dc.workspace_id AND wm.user_id = dcm.user_id
WHERE dcm.conversation_id = ?1
  AND dcm.user_id = ?2
`

type RequireDirectMembershipParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) RequireDirectMembership(ctx context.Context, arg RequireDirectMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, requireDirectMembership, arg.ConversationID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const requireMembership = `-- name: RequireMembership :one
SELECT 1
FROM workspace_members
WHERE workspace_id = ?1
  AND user_id = ?2
`

type RequireMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) RequireMembership(ctx context.Context, arg RequireMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, requireMembership, arg.WorkspaceID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const threadNextSeq = `-- name: ThreadNextSeq :one
SELECT CAST(COALESCE(MAX(thread_seq), 0) + 1 AS INTEGER) AS next_seq
FROM messages
WHERE thread_root_id = ?1
  AND parent_message_id = ?2
`

type ThreadNextSeqParams struct {
	ThreadRootID    string         `json:"thread_root_id"`
	ParentMessageID sql.NullString `json:"parent_message_id"`
}

func (q *Queries) ThreadNextSeq(ctx context.Context, arg ThreadNextSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, threadNextSeq, arg.ThreadRootID, arg.ParentMessageID)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}

const touchBotToken = `-- name: TouchBotToken :exec
UPDATE bot_tokens
SET last_used_at = ?1
WHERE id = ?2
`

type TouchBotTokenParams struct {
	LastUsedAt sql.NullString `json:"last_used_at"`
	ID         string         `json:"id"`
}

func (q *Queries) TouchBotToken(ctx context.Context, arg TouchBotTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchBotToken, arg.LastUsedAt, arg.ID)
	return err
}

const updateChannel = `-- name: UpdateChannel :exec
UPDATE channels
SET name = ?1,
    kind = ?2,
    archived_at = ?3
WHERE id = ?4
`

type UpdateChannelParams struct {
	Name       string         `json:"name"`
	Kind       string         `json:"kind"`
	ArchivedAt sql.NullString `json:"archived_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) error {
	_, err := q.db.ExecContext(ctx, updateChannel,
		arg.Name,
		arg.Kind,
		arg.ArchivedAt,
		arg.ID,
	)
	return err
}

const updateMessageBody = `-- name: UpdateMessageBody :exec
UPDATE messages
SET body = ?1,
    edited_at = ?2
WHERE id = ?3
`

type UpdateMessageBodyParams struct {
	Body     string         `json:"body"`
	EditedAt sql.NullString `json:"edited_at"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageBody, arg.Body, arg.EditedAt, arg.ID)
	return err
}

const updateThreadState = `-- name: UpdateThreadState :exec
UPDATE thread_state
SET reply_count = reply_count + 1,
    last_reply_at = ?1,
    last_reply_author_ids_json = ?2
WHERE root_message_id = ?3
`

type UpdateThreadStateParams struct {
	LastReplyAt            sql.NullString `json:"last_reply_at"`
	LastReplyAuthorIdsJson string         `json:"last_reply_author_ids_json"`
	RootMessageID          string         `json:"root_message_id"`
}

func (q *Queries) UpdateThreadState(ctx context.Context, arg UpdateThreadStateParams) error {
	_, err := q.db.ExecContext(ctx, updateThreadState, arg.LastReplyAt, arg.LastReplyAuthorIdsJson, arg.RootMessageID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = ?1,
    handle = ?2,
    avatar_url = ?3
WHERE id = ?4
`

type UpdateUserProfileParams struct {
	DisplayName string `json:"display_name"`
	Handle      string `json:"handle"`
	AvatarUrl   string `json:"avatar_url"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.ID,
	)
	return err
}

const upsertChannelRead = `-- name: UpsertChannelRead :exec
INSERT INTO channel_reads (channel_id, user_id, last_read_seq, last_read_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(channel_id, user_id) DO UPDATE SET
  last_read_seq = excluded.last_read_seq,
  last_read_at = excluded.last_read_at
`

type UpsertChannelReadParams struct {
	ChannelID   string `json:"channel_id"`
	UserID      string `json:"user_id"`
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

func (q *Queries) UpsertChannelRead(ctx context.Context, arg UpsertChannelReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelRead,
		arg.ChannelID,
		arg.UserID,
		arg.LastReadSeq,
		arg.LastReadAt,
	)
	return err
}

const upsertDirectRead = `-- name: UpsertDirectRead :exec
INSERT INTO direct_reads (conversation_id, user_id, last_read_seq, last_read_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(conversation_id, user_id) DO UPDATE SET
  last_read_seq = excluded.last_read_seq,
  last_read_at = excluded.last_read_at
`

type UpsertDirectReadParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	LastReadSeq    int64  `json:"last_read_seq"`
	LastReadAt     string `json:"last_read_at"`
}

func (q *Queries) UpsertDirectRead(ctx context.Context, arg UpsertDirectReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertDirectRead,
		arg.ConversationID,
		arg.UserID,
		arg.LastReadSeq,
		arg.LastReadAt,
	)
	return err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :exec
INSERT INTO user_notification_settings (user_id, pushover_enabled, pushover_user_key)
VALUES (?1, ?2, ?3)
ON CONFLICT(user_id) DO UPDATE SET
  pushover_enabled = excluded.pushover_enabled,
  pushover_user_key = excluded.pushover_user_key
`

type UpsertNotificationSettingsParams struct {
	UserID          string `json:"user_id"`
	PushoverEnabled int64  `json:"pushover_enabled"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationSettings, arg.UserID, arg.PushoverEnabled, arg.PushoverUserKey)
	return err
}
