// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const attachUpload = `-- name: AttachUpload :exec
INSERT OR IGNORE INTO message_attachments (message_id, upload_id, created_at)
VALUES (?1, ?2, ?3)
`

type AttachUploadParams struct {
	MessageID string `json:"message_id"`
	UploadID  string `json:"upload_id"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) AttachUpload(ctx context.Context, arg AttachUploadParams) error {
	_, err := q.db.ExecContext(ctx, attachUpload, arg.MessageID, arg.UploadID, arg.CreatedAt)
	return err
}

const channelLastSeq = `-- name: ChannelLastSeq :one
SELECT CAST(COALESCE(MAX(channel_seq), 0) AS INTEGER) AS last_seq
FROM messages
WHERE channel_id = CAST(?1 AS TEXT)
  AND parent_message_id IS NULL
`

func (q *Queries) ChannelLastSeq(ctx context.Context, channelID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, channelLastSeq, channelID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const deleteMessageBody = `-- name: DeleteMessageBody :exec
UPDATE messages
SET body = '',
    deleted_at = ?1
WHERE id = ?2
`

type DeleteMessageBodyParams struct {
	DeletedAt sql.NullString `json:"deleted_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteMessageBody(ctx context.Context, arg DeleteMessageBodyParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageBody, arg.DeletedAt, arg.ID)
	return err
}

const directLastSeq = `-- name: DirectLastSeq :one
SELECT CAST(COALESCE(MAX(channel_seq), 0) AS INTEGER) AS last_seq
FROM messages
WHERE direct_conversation_id = CAST(?1 AS TEXT)
  AND parent_message_id IS NULL
`

func (q *Queries) DirectLastSeq(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, directLastSeq, conversationID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const firstUser = `-- name: FirstUser :one
SELECT id, kind, owner_user_id, display_name, handle, avatar_url, created_at
FROM users
ORDER BY created_at
LIMIT 1
`

type FirstUserRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) FirstUser(ctx context.Context) (FirstUserRow, error) {
	row := q.db.QueryRowContext(ctx, firstUser)
	var i FirstUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const firstWorkspace = `-- name: FirstWorkspace :one
SELECT id, COALESCE(route_id, '') AS route_id, name, slug, created_at
FROM workspaces
ORDER BY created_at
LIMIT 1
`

type FirstWorkspaceRow struct {
	ID        string `json:"id"`
	RouteID   string `json:"route_id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) FirstWorkspace(ctx context.Context) (FirstWorkspaceRow, error) {
	row := q.db.QueryRowContext(ctx, firstWorkspace)
	var i FirstWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getBotTokenAuth = `-- name: GetBotTokenAuth :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at,
       bt.id AS token_id, bt.workspace_id, bt.scopes_json
FROM bot_tokens bt
JOIN users u ON u.id = bt.bot_user_id
WHERE bt.token_hash = ?1
  AND bt.revoked_at IS NULL
`

type GetBotTokenAuthRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
	TokenID     string         `json:"token_id"`
	WorkspaceID string         `json:"workspace_id"`
	ScopesJson  string         `json:"scopes_json"`
}

func (q *Queries) GetBotTokenAuth(ctx context.Context, tokenHash string) (GetBotTokenAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getBotTokenAuth, tokenHash)
	var i GetBotTokenAuthRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.TokenID,
		&i.WorkspaceID,
		&i.ScopesJson,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, COALESCE(route_id, '') AS route_id, workspace_id, name, kind, created_at, archived_at
FROM channels
WHERE id = ?1
`

type GetChannelRow struct {
	ID          string         `json:"id"`
	RouteID     string         `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
	ArchivedAt  sql.NullString `json:"archived_at"`
}

func (q *Queries) GetChannel(ctx context.Context, id string) (GetChannelRow, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.WorkspaceID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getChannelWorkspace = `-- name: GetChannelWorkspace :one
SELECT workspace_id
FROM channels
WHERE id = ?1
`

func (q *Queries) GetChannelWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getChannelWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getDirectConversationWorkspace = `-- name: GetDirectConversationWorkspace :one
SELECT workspace_id
FROM direct_conversations
WHERE id = ?1
`

func (q *Queries) GetDirectConversationWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDirectConversationWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getMagicLinkByToken = `-- name: GetMagicLinkByToken :one
SELECT id, token, email, display_name, created_at, expires_at, used_at
FROM auth_magic_links
WHERE token = ?1
`

func (q *Queries) GetMagicLinkByToken(ctx context.Context, token string) (AuthMagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkByToken, token)
	var i AuthMagicLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT pushover_enabled, pushover_user_key
FROM user_notification_settings
WHERE user_id = ?1
`

type GetNotificationSettingsRow struct {
	PushoverEnabled int64  `json:"pushover_enabled"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) GetNotificationSettings(ctx context.Context, userID string) (GetNotificationSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSettings, userID)
	var i GetNotificationSettingsRow
	err := row.Scan(&i.PushoverEnabled, &i.PushoverUserKey)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ?1
  AND s.revoked_at IS NULL
  AND s.expires_at > ?2
`

type GetSessionUserParams struct {
	Token string `json:"token"`
	Now   string `json:"now"`
}

type GetSessionUserRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.Token, arg.Now)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, workspace_id, owner_id, filename, content_type, byte_size, width, height, duration_ms, storage_path, created_at
FROM uploads
WHERE id = ?1
`

type GetUploadRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	OwnerID     string `json:"owner_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
	Width       int64  `json:"width"`
	Height      int64  `json:"height"`
	DurationMs  int64  `json:"duration_ms"`
	StoragePath string `json:"storage_path"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) GetUpload(ctx context.Context, id string) (GetUploadRow, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i GetUploadRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadWorkspace = `-- name: GetUploadWorkspace :one
SELECT workspace_id
FROM uploads
WHERE id = ?1
`

func (q *Queries) GetUploadWorkspace(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUploadWorkspace, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getUser = `-- name: GetUser :one
SELECT id, kind, owner_user_id, display_name, handle, avatar_url, created_at
FROM users
WHERE id = ?1
`

type GetUserRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIdentityEmail = `-- name: GetUserByIdentityEmail :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM identities i
JOIN users u ON u.id = i.user_id
WHERE i.email = ?1
ORDER BY u.created_at
LIMIT 1
`

type GetUserByIdentityEmailRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetUserByIdentityEmail(ctx context.Context, email string) (GetUserByIdentityEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentityEmail, email)
	var i GetUserByIdentityEmailRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByIdentityProviderSubject = `-- name: GetUserByIdentityProviderSubject :one
SELECT u.id, u.kind, u.owner_user_id, u.display_name, u.handle, u.avatar_url, u.created_at
FROM identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = ?1
  AND i.provider_subject = ?2
`

type GetUserByIdentityProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

type GetUserByIdentityProviderSubjectRow struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetUserByIdentityProviderSubject(ctx context.Context, arg GetUserByIdentityProviderSubjectParams) (GetUserByIdentityProviderSubjectRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentityProviderSubject, arg.Provider, arg.ProviderSubject)
	var i GetUserByIdentityProviderSubjectRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.OwnerUserID,
		&i.DisplayName,
		&i.Handle,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertBotToken = `-- name: InsertBotToken :exec
INSERT INTO bot_tokens (id, token_hash, bot_user_id, workspace_id, owner_user_id, name, scopes_json, created_by, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
`

type InsertBotTokenParams struct {
	ID          string         `json:"id"`
	TokenHash   string         `json:"token_hash"`
	BotUserID   string         `json:"bot_user_id"`
	WorkspaceID string         `json:"workspace_id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	Name        string         `json:"name"`
	ScopesJson  string         `json:"scopes_json"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertBotToken(ctx context.Context, arg InsertBotTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertBotToken,
		arg.ID,
		arg.TokenHash,
		arg.BotUserID,
		arg.WorkspaceID,
		arg.OwnerUserID,
		arg.Name,
		arg.ScopesJson,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertBotUser = `-- name: InsertBotUser :exec
INSERT INTO users (id, kind, owner_user_id, display_name, handle, avatar_url, created_at)
VALUES (?1, 'bot', ?2, ?3, ?4, ?5, ?6)
`

type InsertBotUserParams struct {
	ID          string         `json:"id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	DisplayName string         `json:"display_name"`
	Handle      string         `json:"handle"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertBotUser(ctx context.Context, arg InsertBotUserParams) error {
	_, err := q.db.ExecContext(ctx, insertBotUser,
		arg.ID,
		arg.OwnerUserID,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertDefaultChannel = `-- name: InsertDefaultChannel :exec
INSERT INTO channels (id, route_id, workspace_id, name, kind, created_at)
VALUES (?1, ?2, ?3, 'general', 'public', ?4)
`

type InsertDefaultChannelParams struct {
	ID          string         `json:"id"`
	RouteID     sql.NullString `json:"route_id"`
	WorkspaceID string         `json:"workspace_id"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertDefaultChannel(ctx context.Context, arg InsertDefaultChannelParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultChannel,
		arg.ID,
		arg.RouteID,
		arg.WorkspaceID,
		arg.CreatedAt,
	)
	return err
}

const insertDefaultWorkspaceMember = `-- name: InsertDefaultWorkspaceMember :exec
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, created_at)
VALUES (?1, ?2, 'member', ?3)
`

type InsertDefaultWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertDefaultWorkspaceMember(ctx context.Context, arg InsertDefaultWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertDefaultWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.CreatedAt)
	return err
}

const insertHumanUser = `-- name: InsertHumanUser :exec
INSERT INTO users (id, display_name, avatar_url, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertHumanUserParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertHumanUser(ctx context.Context, arg InsertHumanUserParams) error {
	_, err := q.db.ExecContext(ctx, insertHumanUser,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO identities (id, user_id, provider, provider_subject, email, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertIdentityParams struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites (id, workspace_id, token, created_by, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertInviteParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Token       string `json:"token"`
	CreatedBy   string `json:"created_by"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.Token,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertMagicLink = `-- name: InsertMagicLink :exec
INSERT INTO auth_magic_links (id, token, email, display_name, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type InsertMagicLinkParams struct {
	ID          string `json:"id"`
	Token       string `json:"token"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) InsertMagicLink(ctx context.Context, arg InsertMagicLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertMagicLink,
		arg.ID,
		arg.Token,
		arg.Email,
		arg.DisplayName,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, token, user_id, created_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertSessionParams struct {
	ID        string `json:"id"`
	Token     string `json:"token"`
	UserID    string `json:"user_id"`
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertUpload = `-- name: InsertUpload :exec
INSERT INTO uploads (id, workspace_id, owner_id, filename, content_type, byte_size, width, height, duration_ms, storage_path, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
`

type InsertUploadParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	OwnerID     string `json:"owner_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
	Width       int64  `json:"width"`
	Height      int64  `json:"height"`
	DurationMs  int64  `json:"duration_ms"`
	StoragePath string `json:"storage_path"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertUpload(ctx context.Context, arg InsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, insertUpload,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.StoragePath,
		arg.CreatedAt,
	)
	return err
}

const insertWorkspace = `-- name: InsertWorkspace :exec
INSERT INTO workspaces (id, route_id, name, slug, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertWorkspaceParams struct {
	ID        string         `json:"id"`
	RouteID   sql.NullString `json:"route_id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspace,
		arg.ID,
		arg.RouteID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	return err
}

const insertWorkspaceMember = `-- name: InsertWorkspaceMember :exec
INSERT OR IGNORE INTO workspace_members (workspace_id, user_id, role, created_at)
VALUES (?1, ?2, ?3, ?4)
`

type InsertWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) InsertWorkspaceMember(ctx context.Context, arg InsertWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const listDirectPushNotificationRecipients = `-- name: ListDirectPushNotificationRecipients :many
SELECT u.id AS user_id, u.display_name, uns.pushover_user_key
FROM direct_conversation_members dcm
JOIN users u ON u.id = dcm.user_id
JOIN user_notification_settings uns ON uns.user_id = u.id
WHERE dcm.conversation_id = ?1
  AND u.id <> ?2
  AND uns.pushover_enabled = 1
  AND uns.pushover_user_key <> ''
ORDER BY u.id
`

type ListDirectPushNotificationRecipientsParams struct {
	ConversationID string `json:"conversation_id"`
	AuthorID       string `json:"author_id"`
}

type ListDirectPushNotificationRecipientsRow struct {
	UserID          string `json:"user_id"`
	DisplayName     string `json:"display_name"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) ListDirectPushNotificationRecipients(ctx context.Context, arg ListDirectPushNotificationRecipientsParams) ([]ListDirectPushNotificationRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectPushNotificationRecipients, arg.ConversationID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectPushNotificationRecipientsRow
	for rows.Next() {
		var i ListDirectPushNotificationRecipientsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.PushoverUserKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacePushNotificationRecipients = `-- name: ListWorkspacePushNotificationRecipients :many
SELECT u.id AS user_id, u.display_name, uns.pushover_user_key
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
JOIN user_notification_settings uns ON uns.user_id = u.id
WHERE wm.workspace_id = ?1
  AND u.id <> ?2
  AND uns.pushover_enabled = 1
  AND uns.pushover_user_key <> ''
ORDER BY u.id
`

type ListWorkspacePushNotificationRecipientsParams struct {
	WorkspaceID string `json:"workspace_id"`
	AuthorID    string `json:"author_id"`
}

type ListWorkspacePushNotificationRecipientsRow struct {
	UserID          string `json:"user_id"`
	DisplayName     string `json:"display_name"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) ListWorkspacePushNotificationRecipients(ctx context.Context, arg ListWorkspacePushNotificationRecipientsParams) ([]ListWorkspacePushNotificationRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacePushNotificationRecipients, arg.WorkspaceID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacePushNotificationRecipientsRow
	for rows.Next() {
		var i ListWorkspacePushNotificationRecipientsRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.PushoverUserKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE auth_magic_links
SET used_at = ?1
WHERE id = ?2
`

type MarkMagicLinkUsedParams struct {
	UsedAt sql.NullString `json:"used_at"`
	ID     string         `json:"id"`
}

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, arg MarkMagicLinkUsedParams) error {
	_, err := q.db.ExecContext(ctx, markMagicLinkUsed, arg.UsedAt, arg.ID)
	return err
}

const pruneEvents = `-- name: PruneEvents :execrows
DELETE FROM events AS e
WHERE e.workspace_id = ?1
  AND (CAST(?2 AS TEXT) = '' OR julianday(e.created_at) < julianday(CAST(?2 AS TEXT)))
  AND e.id NOT IN (
    SELECT kept.id
    FROM events AS kept
    WHERE kept.workspace_id = ?1
    ORDER BY kept.cursor DESC
    LIMIT ?3
  )
`

type PruneEventsParams struct {
	WorkspaceIDArg string `json:"workspace_id_arg"`
	Before         string `json:"before"`
	KeepLatest     int64  `json:"keep_latest"`
}

func (q *Queries) PruneEvents(ctx context.Context, arg PruneEventsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneEvents, arg.WorkspaceIDArg, arg.Before, arg.KeepLatest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const readChannelRead = `-- name: ReadChannelRead :one
SELECT last_read_seq, last_read_at
FROM channel_reads
WHERE channel_id = ?1
  AND user_id = ?2
`

type ReadChannelReadParams struct {
	ChannelID string `json:"channel_id"`
	UserID    string `json:"user_id"`
}

type ReadChannelReadRow struct {
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

func (q *Queries) ReadChannelRead(ctx context.Context, arg ReadChannelReadParams) (ReadChannelReadRow, error) {
	row := q.db.QueryRowContext(ctx, readChannelRead, arg.ChannelID, arg.UserID)
	var i ReadChannelReadRow
	err := row.Scan(&i.LastReadSeq, &i.LastReadAt)
	return i, err
}

const readDirectRead = `-- name: ReadDirectRead :one
SELECT last_read_seq, last_read_at
FROM direct_reads
WHERE conversation_id = ?1
  AND user_id = ?2
`

type ReadDirectReadParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
}

type ReadDirectReadRow struct {
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

func (q *Queries) ReadDirectRead(ctx context.Context, arg ReadDirectReadParams) (ReadDirectReadRow, error) {
	row := q.db.QueryRowContext(ctx, readDirectRead, arg.ConversationID, arg.UserID)
	var i ReadDirectReadRow
	err := row.Scan(&i.LastReadSeq, &i.LastReadAt)
	return i, err
}

const requireMembership = `-- name: RequireMembership :one
SELECT 1
FROM workspace_members
WHERE workspace_id = ?1
  AND user_id = ?2
`

type RequireMembershipParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) RequireMembership(ctx context.Context, arg RequireMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, requireMembership, arg.WorkspaceID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchBotToken = `-- name: TouchBotToken :exec
UPDATE bot_tokens
SET last_used_at = ?1
WHERE id = ?2
`

type TouchBotTokenParams struct {
	LastUsedAt sql.NullString `json:"last_used_at"`
	ID         string         `json:"id"`
}

func (q *Queries) TouchBotToken(ctx context.Context, arg TouchBotTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchBotToken, arg.LastUsedAt, arg.ID)
	return err
}

const updateChannel = `-- name: UpdateChannel :exec
UPDATE channels
SET name = ?1,
    kind = ?2,
    archived_at = ?3
WHERE id = ?4
`

type UpdateChannelParams struct {
	Name       string         `json:"name"`
	Kind       string         `json:"kind"`
	ArchivedAt sql.NullString `json:"archived_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) error {
	_, err := q.db.ExecContext(ctx, updateChannel,
		arg.Name,
		arg.Kind,
		arg.ArchivedAt,
		arg.ID,
	)
	return err
}

const updateMessageBody = `-- name: UpdateMessageBody :exec
UPDATE messages
SET body = ?1,
    edited_at = ?2
WHERE id = ?3
`

type UpdateMessageBodyParams struct {
	Body     string         `json:"body"`
	EditedAt sql.NullString `json:"edited_at"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageBody, arg.Body, arg.EditedAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET display_name = ?1,
    handle = ?2,
    avatar_url = ?3
WHERE id = ?4
`

type UpdateUserProfileParams struct {
	DisplayName string `json:"display_name"`
	Handle      string `json:"handle"`
	AvatarUrl   string `json:"avatar_url"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Handle,
		arg.AvatarUrl,
		arg.ID,
	)
	return err
}

const upsertChannelRead = `-- name: UpsertChannelRead :exec
INSERT INTO channel_reads (channel_id, user_id, last_read_seq, last_read_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(channel_id, user_id) DO UPDATE SET
  last_read_seq = excluded.last_read_seq,
  last_read_at = excluded.last_read_at
`

type UpsertChannelReadParams struct {
	ChannelID   string `json:"channel_id"`
	UserID      string `json:"user_id"`
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

func (q *Queries) UpsertChannelRead(ctx context.Context, arg UpsertChannelReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelRead,
		arg.ChannelID,
		arg.UserID,
		arg.LastReadSeq,
		arg.LastReadAt,
	)
	return err
}

const upsertDirectRead = `-- name: UpsertDirectRead :exec
INSERT INTO direct_reads (conversation_id, user_id, last_read_seq, last_read_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(conversation_id, user_id) DO UPDATE SET
  last_read_seq = excluded.last_read_seq,
  last_read_at = excluded.last_read_at
`

type UpsertDirectReadParams struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	LastReadSeq    int64  `json:"last_read_seq"`
	LastReadAt     string `json:"last_read_at"`
}

func (q *Queries) UpsertDirectRead(ctx context.Context, arg UpsertDirectReadParams) error {
	_, err := q.db.ExecContext(ctx, upsertDirectRead,
		arg.ConversationID,
		arg.UserID,
		arg.LastReadSeq,
		arg.LastReadAt,
	)
	return err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :exec
INSERT INTO user_notification_settings (user_id, pushover_enabled, pushover_user_key)
VALUES (?1, ?2, ?3)
ON CONFLICT(user_id) DO UPDATE SET
  pushover_enabled = excluded.pushover_enabled,
  pushover_user_key = excluded.pushover_user_key
`

type UpsertNotificationSettingsParams struct {
	UserID          string `json:"user_id"`
	PushoverEnabled int64  `json:"pushover_enabled"`
	PushoverUserKey string `json:"pushover_user_key"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationSettings, arg.UserID, arg.PushoverEnabled, arg.PushoverUserKey)
	return err
}
