// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type AuthMagicLink struct {
	ID          string         `json:"id"`
	Token       string         `json:"token"`
	TokenHash   string         `json:"token_hash"`
	Email       string         `json:"email"`
	DisplayName string         `json:"display_name"`
	CreatedAt   string         `json:"created_at"`
	ExpiresAt   string         `json:"expires_at"`
	UsedAt      sql.NullString `json:"used_at"`
}

type BotToken struct {
	ID          string         `json:"id"`
	TokenHash   string         `json:"token_hash"`
	BotUserID   string         `json:"bot_user_id"`
	WorkspaceID string         `json:"workspace_id"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
	Name        string         `json:"name"`
	ScopesJson  string         `json:"scopes_json"`
	CreatedBy   sql.NullString `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type Channel struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Kind        string         `json:"kind"`
	CreatedAt   string         `json:"created_at"`
	ArchivedAt  sql.NullString `json:"archived_at"`
	RouteID     sql.NullString `json:"route_id"`
}

type ChannelRead struct {
	ChannelID   string `json:"channel_id"`
	UserID      string `json:"user_id"`
	LastReadSeq int64  `json:"last_read_seq"`
	LastReadAt  string `json:"last_read_at"`
}

type DirectConversation struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	CreatedAt   string         `json:"created_at"`
	RouteID     sql.NullString `json:"route_id"`
}

type DirectConversationMember struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	CreatedAt      string `json:"created_at"`
}

type DirectRead struct {
	ConversationID string `json:"conversation_id"`
	UserID         string `json:"user_id"`
	LastReadSeq    int64  `json:"last_read_seq"`
	LastReadAt     string `json:"last_read_at"`
}

type Event struct {
	ID          string         `json:"id"`
	Cursor      string         `json:"cursor"`
	WorkspaceID string         `json:"workspace_id"`
	ChannelID   sql.NullString `json:"channel_id"`
	Type        string         `json:"type"`
	Seq         sql.NullInt64  `json:"seq"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   string         `json:"created_at"`
	IsPrivate   int64          `json:"is_private"`
}

type EventRecipient struct {
	EventID string `json:"event_id"`
	UserID  string `json:"user_id"`
}

type Identity struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
	CreatedAt       string `json:"created_at"`
}

type Invite struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Token       string         `json:"token"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   string         `json:"created_at"`
	AcceptedAt  sql.NullString `json:"accepted_at"`
}

type Message struct {
	ID                   string         `json:"id"`
	WorkspaceID          string         `json:"workspace_id"`
	ChannelID            sql.NullString `json:"channel_id"`
	DirectConversationID sql.NullString `json:"direct_conversation_id"`
	AuthorID             string         `json:"author_id"`
	ParentMessageID      sql.NullString `json:"parent_message_id"`
	ThreadRootID         string         `json:"thread_root_id"`
	ChannelSeq           sql.NullInt64  `json:"channel_seq"`
	ThreadSeq            sql.NullInt64  `json:"thread_seq"`
	Body                 string         `json:"body"`
	BodyFormat           string         `json:"body_format"`
	CreatedAt            string         `json:"created_at"`
	EditedAt             sql.NullString `json:"edited_at"`
	DeletedAt            sql.NullString `json:"deleted_at"`
	QuotedMessageID      sql.NullString `json:"quoted_message_id"`
	QuotedBodySnapshot   string         `json:"quoted_body_snapshot"`
	QuotedAuthorID       sql.NullString `json:"quoted_author_id"`
	ClientNonce          string         `json:"client_nonce"`
	RouteID              sql.NullString `json:"route_id"`
}

type MessageAttachment struct {
	MessageID string `json:"message_id"`
	UploadID  string `json:"upload_id"`
	CreatedAt string `json:"created_at"`
}

type Reaction struct {
	MessageID string `json:"message_id"`
	UserID    string `json:"user_id"`
	Emoji     string `json:"emoji"`
	CreatedAt string `json:"created_at"`
}

type Session struct {
	ID        string         `json:"id"`
	Token     string         `json:"token"`
	TokenHash string         `json:"token_hash"`
	UserID    string         `json:"user_id"`
	CreatedAt string         `json:"created_at"`
	ExpiresAt string         `json:"expires_at"`
	RevokedAt sql.NullString `json:"revoked_at"`
}

type ThreadState struct {
	RootMessageID          string         `json:"root_message_id"`
	ReplyCount             int64          `json:"reply_count"`
	LastReplyAt            sql.NullString `json:"last_reply_at"`
	LastReplyAuthorIdsJson string         `json:"last_reply_author_ids_json"`
}

type Upload struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	OwnerID     string `json:"owner_id"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
	StoragePath string `json:"storage_path"`
	CreatedAt   string `json:"created_at"`
	Width       int64  `json:"width"`
	Height      int64  `json:"height"`
	DurationMs  int64  `json:"duration_ms"`
}

type UploadQuotaReservation struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	OwnerID     string `json:"owner_id"`
	ByteSize    int64  `json:"byte_size"`
	CreatedAt   string `json:"created_at"`
	ExpiresAt   string `json:"expires_at"`
}

type User struct {
	ID          string         `json:"id"`
	DisplayName string         `json:"display_name"`
	AvatarUrl   string         `json:"avatar_url"`
	CreatedAt   string         `json:"created_at"`
	Handle      string         `json:"handle"`
	Kind        string         `json:"kind"`
	OwnerUserID sql.NullString `json:"owner_user_id"`
}

type UserNotificationSetting struct {
	UserID          string `json:"user_id"`
	PushoverEnabled int64  `json:"pushover_enabled"`
	PushoverUserKey string `json:"pushover_user_key"`
}

type Workspace struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	CreatedAt string         `json:"created_at"`
	RouteID   sql.NullString `json:"route_id"`
}

type WorkspaceMember struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
	CreatedAt   string `json:"created_at"`
}

type WorkspaceMemberModeration struct {
	WorkspaceID    string         `json:"workspace_id"`
	UserID         string         `json:"user_id"`
	TimeoutUntil   sql.NullString `json:"timeout_until"`
	BlockedAt      sql.NullString `json:"blocked_at"`
	ModerationNote string         `json:"moderation_note"`
	ModerationBy   sql.NullString `json:"moderation_by"`
	ModerationAt   string         `json:"moderation_at"`
}
